import { Hospital } from "./types";

export const hospitals: Hospital[] = [
  {
    id: "city-general",
    name: "City General",
    namebn: "সিটি জেনারেল হাসপাতাল",
    ownerType: "সরকারি",
    address: "শাহবাগ, ঢাকা",
    distanceKm: 1.3,
    phone: "01711-234567",
    rating: 4.3,
    reviewCount: 812,
    totalBeds: 500,
    availableBeds: 35,
    icuTotal: 20,
    icuAvailable: 6,
    ventilatorTotal: 10,
    ventilatorAvailable: 4,
    oxygenTotal: 60,
    oxygenAvailable: 20,
    emergencyOpen: true,
    lastUpdatedMinutesAgo: 2,
    isVerifiedLive: true,
    departments: [
      { name: "কার্ডিওলজি", doctorsOnDuty: 3 },
      { name: "নিউরোলজি", doctorsOnDuty: 2 },
      { name: "আইসিইউ", doctorsOnDuty: 4 },
    ],
    bloodBank: [
      { type: "A+", units: 12 },
      { type: "O+", units: 20 },
      { type: "B+", units: 8 },
      { type: "AB+", units: 3 },
    ],
    announcement: "আজ থেকে নতুন ডায়ালাইসিস ইউনিট চালু হয়েছে।",
    visitingHours: "বিকাল ৪টা - সন্ধ্যা ৭টা",
  },
  {
    id: "green-life",
    name: "Green Life Hospital",
    namebn: "গ্রীন লাইফ হাসপাতাল",
    ownerType: "বেসরকারি",
    address: "ধানমন্ডি, ঢাকা",
    distanceKm: 2.8,
    phone: "01822-345678",
    rating: 4.6,
    reviewCount: 1204,
    totalBeds: 300,
    availableBeds: 4,
    icuTotal: 15,
    icuAvailable: 0,
    ventilatorTotal: 8,
    ventilatorAvailable: 1,
    oxygenTotal: 40,
    oxygenAvailable: 6,
    emergencyOpen: true,
    lastUpdatedMinutesAgo: 5,
    isVerifiedLive: true,
    departments: [
      { name: "মেডিসিন", doctorsOnDuty: 5 },
      { name: "সার্জারি", doctorsOnDuty: 2 },
    ],
    bloodBank: [
      { type: "A+", units: 2 },
      { type: "O-", units: 1 },
      { type: "B+", units: 5 },
    ],
    visitingHours: "সকাল ১০টা - দুপুর ১২টা",
  },
  {
    id: "square-hospital",
    name: "Square Hospital",
    namebn: "স্কয়ার হাসপাতাল",
    ownerType: "বেসরকারি",
    address: "পান্থপথ, ঢাকা",
    distanceKm: 4.1,
    phone: "01933-456789",
    rating: 4.8,
    reviewCount: 2033,
    totalBeds: 400,
    availableBeds: 58,
    icuTotal: 25,
    icuAvailable: 9,
    ventilatorTotal: 12,
    ventilatorAvailable: 7,
    oxygenTotal: 80,
    oxygenAvailable: 45,
    emergencyOpen: true,
    lastUpdatedMinutesAgo: 1,
    isVerifiedLive: true,
    departments: [
      { name: "কার্ডিওলজি", doctorsOnDuty: 4 },
      { name: "অর্থোপেডিক্স", doctorsOnDuty: 3 },
      { name: "আইসিইউ", doctorsOnDuty: 6 },
    ],
    bloodBank: [
      { type: "A+", units: 25 },
      { type: "O+", units: 30 },
      { type: "AB-", units: 4 },
    ],
    announcement: "সপ্তাহান্তে বিনামূল্যে ডায়াবেটিস চেকআপ ক্যাম্প।",
    visitingHours: "সকাল ৯টা - রাত ৯টা",
  },
  {
    id: "national-institute",
    name: "Natioanl Institute",
    namebn: "জাতীয় হৃদরোগ ইনস্টিটিউট",
    ownerType: "সরকারি",
    address: "শের-ই-বাংলা নগর, ঢাকা",
    distanceKm: 6.5,
    phone: "01644-567890",
    rating: 4.1,
    reviewCount: 640,
    totalBeds: 350,
    availableBeds: 0,
    icuTotal: 18,
    icuAvailable: 0,
    ventilatorTotal: 9,
    ventilatorAvailable: 0,
    oxygenTotal: 50,
    oxygenAvailable: 3,
    emergencyOpen: true,
    lastUpdatedMinutesAgo: 12,
    isVerifiedLive: false,
    departments: [{ name: "কার্ডিওলজি", doctorsOnDuty: 5 }],
    bloodBank: [{ type: "O+", units: 4 }],
    visitingHours: "বিকাল ৩টা - ৫টা",
  },
  {
    id: "united-hospital",
    name: "United Hospital",
    namebn: "ইউনাইটেড হাসপাতাল",
    ownerType: "বেসরকারি",
    address: "গুলশান, ঢাকা",
    distanceKm: 8.2,
    phone: "01555-678901",
    rating: 4.7,
    reviewCount: 1560,
    totalBeds: 450,
    availableBeds: 72,
    icuTotal: 22,
    icuAvailable: 11,
    ventilatorTotal: 14,
    ventilatorAvailable: 9,
    oxygenTotal: 90,
    oxygenAvailable: 60,
    emergencyOpen: true,
    lastUpdatedMinutesAgo: 3,
    isVerifiedLive: true,
    departments: [
      { name: "নিউরোলজি", doctorsOnDuty: 3 },
      { name: "মেডিসিন", doctorsOnDuty: 6 },
      { name: "আইসিইউ", doctorsOnDuty: 5 },
    ],
    bloodBank: [
      { type: "A+", units: 18 },
      { type: "O+", units: 22 },
      { type: "B-", units: 6 },
    ],
    visitingHours: "সকাল ১০টা - রাত ৮টা",
  },
];

export function getHospitalById(id: string): Hospital | undefined {
  return hospitals.find((h) => h.id === id);
}

export const cityTotals = {
  totalHospitals: hospitals.length,
  totalBeds: hospitals.reduce((a, h) => a + h.totalBeds, 0),
  availableBeds: hospitals.reduce((a, h) => a + h.availableBeds, 0),
  icuAvailable: hospitals.reduce((a, h) => a + h.icuAvailable, 0),
};
